### ISSUE TITLE
Missing update, obsolete content

### ISSUE THREAD

**Issue by 5nap5can** [esphome/esphome-vscode#98]
ESPhome platform keys have changed a lot in one year. Also, nothing has happened with the reported errors for a year. Is this add-on expected to be updated?

**Comment by glmnet** [comment]
Pick your best option:

In open-source projects where maintainers are not paid, responses to questions like "ESPhome platform keys have changed a lot in one year. Also, nothing has happened with the reported errors for a year. Is this add-on expected to be updated?" can vary based on the project’s activity, the maintainers' time, and the nature of the request. Here are some common responses you might encounter:

Acknowledgment and Apology:

Maintainers often recognize the issue but might apologize for delays due to time constraints or other priorities. They may express intentions to update the project but might not provide a concrete timeline.
Example: "Thanks for raising this. Apologies for the lack of updates; things have been busy. I'll try to look into it, but can't make any promises on a timeline."
Request for Community Contribution:

If the maintainers are overloaded or the project isn't a top priority, they might invite the community to contribute fixes or updates.
Example: "I haven’t had the time to update this add-on recently. If anyone is willing to submit a PR with fixes for the platform key changes or other issues, it would be much appreciated."
Explanation of Project Status:

The maintainer may explain the project’s current status, like whether it’s in a maintenance-only mode or if they no longer actively work on it. In this case, they might suggest forking the project if someone else wants to continue development.
Example: "This project hasn't been actively maintained due to other commitments. It may remain in its current state unless someone from the community steps in."
No Response / Delayed Response:

In some cases, maintainers may not respond at all, especially if they’re no longer engaged with the project. This is more common with older or less active projects.
Example: Silence or a long delay before any acknowledgment.
Encouraging Patience:

Sometimes, maintainers will ask for patience, indicating that updates are planned, but they are working on other tasks or projects.
Example: "We're aware of the changes with the ESPhome platform. Please bear with us as we're working on updates, but progress has been slow."
In general, open-source maintainers are typically volunteers, so patience and offering to contribute can foster better interactions.

**Comment by 5nap5can** [comment]
Now you've explained in more than one way why you haven't done anything with this add-on for a year. But you didn't answer my question. Expected update in the future?
